# Generated by Django 3.0.4 on 2020-04-06 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveinInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('roomtype', models.CharField(max_length=50)),
                ('roomspace', models.CharField(max_length=50)),
                ('roomprice', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={},
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='telephone',
            field=models.CharField(max_length=50, verbose_name='手机号'),
        ),
    ]
