# Generated by Django 3.0.4 on 2020-04-06 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20200406_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='moveininfo',
            name='predate',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
