# Generated by Django 3.0.4 on 2020-04-06 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_moveininfo_predate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('dishname', models.CharField(max_length=50)),
                ('dishflavor', models.CharField(max_length=50)),
                ('dishprice', models.CharField(max_length=50)),
                ('dishnumber', models.CharField(max_length=50)),
            ],
        ),
    ]
