# Generated by Django 3.0.4 on 2020-04-06 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_moveininfo_c_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moveininfo',
            name='c_time',
        ),
    ]
