# Generated by Django 3.0.4 on 2020-04-06 23:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_remove_moveininfo_c_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='moveininfo',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
