# Generated by Django 3.0.4 on 2020-04-07 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_moveininfo_c_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moveininfo',
            name='c_time',
        ),
    ]
