# Generated by Django 3.0.4 on 2020-04-07 00:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_remove_moveininfo_c_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='moveininfo',
            name='movein_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
