# Generated by Django 3.0.4 on 2020-04-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_moveininfo_movein_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='moveininfo',
            name='roomphoto',
            field=models.ImageField(default=1, upload_to='imgs'),
            preserve_default=False,
        ),
    ]
