# Generated by Django 3.0.4 on 2020-04-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_moveininfo_roomstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishinfo',
            name='dishphoto',
            field=models.ImageField(default=0, upload_to='imgs'),
            preserve_default=False,
        ),
    ]
