# Generated by Django 3.0.4 on 2020-04-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_dishinfo_dishphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('tablenumber', models.IntegerField(max_length=30)),
            ],
        ),
    ]
