# Generated by Django 3.0.4 on 2020-04-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_tableinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableinfo',
            name='tablestatus',
            field=models.IntegerField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
