# Generated by Django 3.0.4 on 2020-04-08 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_tableinfo_tablestatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moveininfo',
            name='roomstatus',
        ),
    ]
