# Generated by Django 3.0.4 on 2020-04-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_remove_moveininfo_roomstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='moveininfo',
            name='roomstatus',
            field=models.IntegerField(default=0),
        ),
    ]
