# Generated by Django 3.0.4 on 2020-04-09 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_moveininfo_roomstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('adminname', models.CharField(max_length=30)),
                ('adminpwd', models.CharField(max_length=30)),
            ],
        ),
    ]
