# Generated by Django 3.0.4 on 2020-04-09 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0018_auto_20200409_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admininfo',
            name='adminname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='admininfo',
            name='adminpwd',
            field=models.CharField(max_length=30),
        ),
    ]
