# Generated by Django 3.0.4 on 2020-04-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0019_auto_20200409_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('noticetime', models.DateField(auto_now_add=True)),
                ('noticecontent', models.CharField(max_length=100)),
            ],
        ),
    ]
