# Generated by Django 3.0.4 on 2020-05-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0020_noticeinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLeacots',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('name', models.CharField(max_length=50, verbose_name='用户名')),
                ('leacots', models.CharField(max_length=500, verbose_name='留言')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='moveininfo',
            name='movein_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
